######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 6 11:21:01 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hammer.h knee.h
SOURCES += reflex.cpp
