######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 6 11:47:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ttt.h ttt_board.h ttt_button.h
SOURCES += main.cpp ttt.cpp ttt_board.cpp ttt_button.cpp
