######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 6 11:32:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += form.h
SOURCES += form.cpp formex.cpp
